version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        env_file: .env
        volumes:
            - .:/var/www
            - /var/www/vendor
        ports:
            - "8000:8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: recrut_me_back
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    rabbitmq:
        image: "rabbitmq:management"
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    pgdata:
    rabbitmq-data:
