version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        env_file: .env
        volumes:
            - .:/var/www
            - /var/www/vendor
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        networks:
            - app_network

    postgres:
        image: postgres:15
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: recrut_me_back
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app_network

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - app_network

volumes:
    pgdata:

networks:
    app_network:
        driver: bridge
